FROM ubuntu:16.04
MAINTAINER Kent Knox <kent.knox@amd>

# Parameters related to building hcc-lc
ARG rocm_install_path=/opt/rocm
ARG rocm_build_path=/usr/local/src/hcc-lc
ARG build_type=Release

# Download and install an up to date version of cmake, because compiling
# LLVM has implemented a requirement of cmake v3.4.4 or greater
ARG cmake_prefix=/opt/cmake
ARG cmake_ver_major=3.7
ARG cmake_ver_minor=3.7.2

# Install Packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl && \
    curl -sL http://packages.amd.com/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
    sh -c 'echo deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list' && \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    sudo \
    file \
    build-essential \
    git \
    software-properties-common \
    wget \
    python \
    rpm \
    gcc-multilib \
    g++-multilib \
    libncurses5-dev \
    libelf-dev \
    findutils \
    libpci3 \
    debianutils \
    cmake \
    hsa-rocr-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Compiling hcc-lc requires a custom build tool
RUN curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo && \
    chmod a+x /usr/local/bin/repo

RUN mkdir -p ${rocm_build_path} && \
    cd ${rocm_build_path} && \
    repo init --depth=1 -u https://github.com/RadeonOpenCompute/HCC-Native-GCN-ISA.git -b remove-promote-change-addr-space && \
    repo sync && \

    # build amd-common LLVM/LLD/Clang
    cd ${rocm_build_path}/llvm && \
    mkdir -p build && \
    cd build && \
    cmake \
      -DCMAKE_INSTALL_PREFIX=${rocm_install_path} \
      -DCMAKE_BUILD_TYPE=${build_type} \
      -DLLVM_TARGETS_TO_BUILD="AMDGPU;X86" \
      -DLLVM_APPEND_VC_REV=ON .. && \
    make -j $(nproc) && \

    # build ROCm-Device-Libs with amd-common Clang
    cd ${rocm_build_path}/rocdl/ && \
    mkdir -p build && \
    cd build && \
    CC=${rocm_build_path}/llvm/build/bin/clang cmake \
      -DCMAKE_INSTALL_PREFIX=${rocm_install_path} \
      -DCMAKE_BUILD_TYPE=${build_type} \
      -DAMDHSACOD=/opt/rocm/bin/amdhsacod \
      -DLLVM_DIR="${rocm_build_path}/llvm/build" \
      .. && \
    make -j $(nproc) package && \
    dpkg -i rocm-device-libs-*.deb
