FROM ubuntu:16.04
MAINTAINER Kent Knox <kent.knox@amd>

# Initialize the image we are working with
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y curl && \
  curl -sL http://packages.amd.com/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
  sh -c 'echo deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list' && \
  apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
  hsa-rocr-dev g++-multilib gcc-multilib libstdc++-dev findutils libelf1 libpci3 file && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

# Copy the debian package of hcc-lc into the container from host
COPY *.deb /tmp/

# Install the debian package
RUN dpkg -i /tmp/*.deb && rm -f /tmp/*.deb
