FROM ubuntu:16.04
MAINTAINER Kent Knox <kent.knox@amd>

# Initialize the image we are working with
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y curl && \
  curl -sL http://packages.amd.com/rocm/apt/debian/rocm.gpg.key | apt-key add - && \
  sh -c 'echo deb [arch=amd64] http://packages.amd.com/rocm/apt/debian/ xenial main > /etc/apt/sources.list.d/rocm.list' && \
  apt-get update && \
  apt-get clean

# Copy the debian package of hcc-lc into the container from host
COPY *.deb /tmp/

# Install the debian package
# FIXME: add --allow-unauthenticated to workaround issue with packages.amd.com
RUN apt-get install --no-install-recommends --allow-unauthenticated -y /tmp/hcc*.deb && rm -f /tmp/*.deb
