// RUN: %cxxamp -emit-llvm -S -c %s -o -|c++filt|%FileCheck %s
#include <cstdlib> //for size_t
//Serialization object decl
namespace Concurrency {
class Serialize{};
class gmac_array {
 public:
   void __cxxamp_serialize(Serialize& s);
};
}

class baz {
 public:
  void __cxxamp_serialize(Concurrency::Serialize& s);
 private:
  Concurrency::gmac_array foo;
};

int kerker(void) restrict(amp,cpu) {
  baz b1;
  Concurrency::Serialize s;
  b1.__cxxamp_serialize(s);
  return 1;
}
// The definition should be generated by clang
// CHECK: call {{.*}}void @Concurrency::gmac_array::__cxxamp_serialize
